import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import TopBar from "@/components/top-bar";
import Footer from "@/components/footer";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const domine = Playfair_Display({
  variable: "--font-domine",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${domine.variable} antialiased`}
      >
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
